package SoundLn.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Captor = 0;
  public static final int ContinuousCaptor = 1;
  public static final int ScheduledCaptor = 2;
  public static final int SoundDetector = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1cb3be812ce745bcL, 0xb95047f9080cab09L);
    builder.put(0x6d92a90974855a2bL, Captor);
    builder.put(0x6d92a90974855a38L, ContinuousCaptor);
    builder.put(0x6d92a90974855a30L, ScheduledCaptor);
    builder.put(0x6d92a90974855a2aL, SoundDetector);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
